### ISSUE TITLE
I can not install the driver I do not know how to do it and I do not speak English I can not install help

### ISSUE THREAD

**Issue by joseg-21** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#41]
Hello that such a friend will be that you can help me I have a big problem I could install everything normal the system runs ok update osx to install the video and improve the performance I need to know how to use and how to install the audio driver and the wifi since I really need both for more I've searched and searched almost everything is in English and although I translate and try to do it I can not get it to work realtek alc233 this is my audio coced and try to install the wifi but recognized it bone networks never find them this is my network card qualcomm atheros ar9462 sera that could help me please I have already tried all the pc that is this ES1-572-50TV of the brand acer

**Comment by insanelydeepak** [comment]
Hi 
im from india , i don't know other languages rather than english or regional languages 
you need google translator but it don't work better good enough to use 

 First for Laptop Issue : 
i suggest you to create a post here , they very kind people ,super fast in response and  better in laptop knowledge then me 
http://forum.osxlatitude.com

you can find me there too 

For Audio : 
send your clover folder , i will tell you what and how to do it

**Comment by insanelydeepak** [comment]
Hi 
im closing this issue assume you are not available , feel free to re-open when available
